#!/usr/bin/env bash
echo "==Delete Bucket"

# Check for profile name
if [ -z "$1" ]; then
    echo "There needs to be a oktaws cvent profile name eg. cvent-sandbox"
    exit 1
fi

# Check for bucket name
if [ -z "$2" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

# Delete bucket
aws s3 rb s3://$2 --profile $1 --force
