#!/usr/bin/env bash
echo "==Get Newest Bucket"

# Check for profile name
if [ -z "$1" ]; then
    echo "There needs to be a oktaws cvent profile name eg. cvent-sandbox"
    exit 1
fi

PROFILE_NAME=$1

aws s3api list-buckets --profile $PROFILE_NAME | jq -r '.Buckets | sort_by(.CreationDate) | .[-1].Name'
