AWSTemplateFormatVersion: "2010-09-09"
Description: CFN Stack for creating S3 bucket
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: w502023-iac-cfn-bucket
